module.exports = (con,Sequelize) =>{
    const {STRING,TEXT,INTEGER} = Sequelize
    const Movie = con.define("movie",{
        title:{
            type:STRING(65),
            allowNull:false
        },
        year:{
            type:INTEGER(4),
            allowNull:false
        },
        rated:{
            type:STRING(5),
            allowNull:false
        },
        released:{
            type:STRING(10),
            allowNull:false
        },
        runtime:{
            type:STRING(32),
            allowNull:false
        },
        actors:{
            type:STRING(265),
            allowNull:false
        },
        awards:{
            type:STRING(265),
            allowNull:false
        },
        boxoffice:{
            type:INTEGER(11),
            allowNull:false
        },
        country:{
            type:STRING(65),
            allowNull:false
        },
        dvd:{
            type:STRING(32),
            allowNull:false
        },
        director:{
            type:STRING(65),
            allowNull:false
        },
        genre:{
            type:STRING(65),
            allowNull:false
        },
        language:{
            type:STRING(32),
            allowNull:false
        },
        metascore:{
            type:STRING(65),
            allowNull:false
        },
        plot:{
            type: TEXT,
            allowNull:false
        },
        poster:{
            type:STRING(265),
            allowNull:false
        },
        production:{
            type:STRING(65),
            allowNull:false
        },
        type:{
            type:STRING(32),
            allowNull:false
        },
        website:{
            type:STRING(65),
            allowNull:false
        },
        writer:{
            type:STRING(65),
            allowNull:false
        },        
        year:{
            type:STRING(32),
            allowNull:false
        },
        imdbid:{
            type:STRING(65),
            allowNull:false,
            unique:true
        },
        imdbrating:{
            type:STRING(65),
            allowNull:false
        },
        imdbvotes:{
            type:STRING(65),
            allowNull:false
        }
    },
    {
        hooks:{
            beforeCreate:function(movie){
                movie.boxoffice = movie.boxoffice.substr(1).replace(/,/g, '')
            }
        }
    })
    return Movie
}